services:
  # Create a redis instance
  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: []

  # Let's create our background worker
  - type: worker
    name: sidekiq-worker
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -r ./main.rb
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString

  # Create the web server hosting sinatra
  - type: web
    name: sinatra-web
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec ruby main.rb
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
